project_id = "rdmznweegnutrmpfimoj"
[functions.stripe-webhook-v2]
enabled = true
verify_jwt = true
import_map = "./functions/stripe-webhook-v2/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/stripe-webhook-v2/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/stripe-webhook-v2/*.html" ]
